name: brproxy
description: A library for proxying http requests in the browser.
version: 0.0.1
author: Erik Grimes <erik.grimes@gmail.com>
homepage: https://www.github.com/nameitlater/brproxy

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  http: '^0.11.0'
